Repository mozilla/treeherder, pull requests merged in 2019-11, with the labels that each got.

#5382 Bug 1516630 - delete old frameworks and alerts that are not used
  treeherder/perf/fixtures/performance_bug_templates.yaml
  treeherder/perf/fixtures/performance_framework.json
Labels: python

#5444 Bug 1585966 - Centered header titles from Compare views should be edi…
  tests/ui/perfherder/compare_table_test.jsx
  ui/css/perf.css
  ui/perfherder/compare/ComparePageTitle.jsx
  ui/perfherder/compare/CompareTableView.jsx
Labels: javascript

#5611 Bug 1595018 - Temporarily allow maxLength of 100 for extra options
  schemas/performance-artifact.json
Labels: python

#5612 Bug 1593869 - UI changes in preparation for Taskcluster migration
  .neutrinorc.js
  ui/helpers/url.js
  ui/job-view/details/summary/ActionBar.jsx
  ui/job-view/details/summary/SummaryPanel.jsx
  ui/job-view/pushes/Push.jsx
  ui/logviewer/App.jsx
  ui/models/runnableJob.js
  ui/shared/JobInfo.jsx
Labels: javascript

#5584 Bug 1593190 - Provide backend ORM support for ingesting the application name
  treeherder/perf/migrations/0020_add_application_field.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#5596 Bug 1584946 - Mirror mozilla-central schema change
  schemas/performance-artifact.json
Labels: python

#5595 Bug 1593194 - Mirror schema validation support for application & application version fields from CI
  schemas/performance-artifact.json
Labels: python

#5625 Bug 1593190 - Remove application property
  treeherder/perf/migrations/0021_remove_application_from_constraint.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#5567 Bug 1587017 - Provide display variants for suite & test names
  tests/model/test_suite_public_name.py
  treeherder/perf/migrations/0022_add_test_display_names.py
  treeherder/perf/models.py
  treeherder/webapp/api/performance_serializers.py
Labels: db-schema-changes, python

#5319 Bug 1572516 - Perfherder schema doesn't allow gcp machine names
  tests/log_parser/test_performance_artifact_builder.py
  tests/log_parser/test_utils.py
  treeherder/etl/perf.py
  treeherder/log_parser/parsers.py
  treeherder/log_parser/tasks.py
  treeherder/log_parser/utils.py
  treeherder/perf/migrations/0023_increase_extra_options_size.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#5539 Bug 1571369 - Store backfill reports per alert summary
  tests/conftest.py
  tests/model/test_backfill_report.py
  tests/perfalert/test_alerts/test_backfill_report_maintainer.py
  treeherder/perf/alerts.py
  treeherder/perf/exceptions.py
  treeherder/perf/management/commands/synthesize_backfill_report.py
  treeherder/perf/migrations/0024_support_backfill_reports.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#5637 Bug 1596113 - Log logs with empty performance data
  tests/log_parser/test_performance_parser.py
  treeherder/log_parser/artifactbuildercollection.py
  treeherder/log_parser/parsers.py
Labels: python

#5532 Bug 1587393 - Provide backend support for tagging performance signatures
  tests/etl/test_perf_data_load.py
  treeherder/perf/migrations/0025_provide_tag_support.py
  treeherder/perf/models.py
  treeherder/webapp/api/performance_serializers.py
Labels: db-schema-changes, python

#5646 Bug 1596764 - synthesize_backfill_report commands errors out
  treeherder/perf/alerts.py
Labels: python

#5638 Bug 1593196 - Ingest application field values
  treeherder/etl/perf.py
Labels: python

#5608 Bug 1594064 - Show framework in graph legend
  tests/ui/perfherder/legend_card_test.jsx
  ui/perfherder/constants.js
  ui/perfherder/graphs/LegendCard.jsx
Labels: javascript

#5664 Bug 1597634 - Mirror CI schema support for public suite & test names
  schemas/performance-artifact.json
Labels: javascript

#5659 Bug 1597635 - Ingest public suite & test names, where available
  treeherder/etl/perf.py
Labels: python

#5673 Bug 1587395 - Provide capability of ingesting performance signature tags
  treeherder/etl/perf.py
Labels: python

#5671 Bug 1587401 - Mirror new schema validations on Perfherder
  schemas/performance-artifact.json
Labels: javascript

#5452 Bug 1571411 - Initial test validity dashboard
  tests/ui/perfherder/health_table_test.jsx
  treeherder/webapp/api/machine_platforms.py
  treeherder/webapp/api/serializers.py
  treeherder/webapp/api/urls.py
  ui/css/perf.css
  ui/perfherder/App.jsx
  ui/perfherder/FilterControls.jsx
  ui/perfherder/Navigation.jsx
  ui/perfherder/constants.js
  ui/perfherder/graphs/GraphsContainer.jsx
  ui/perfherder/health/HealthTable.jsx
  ui/perfherder/health/HealthTableControls.jsx
  ui/perfherder/health/HealthView.jsx
  ui/perfherder/health/ItemList.jsx
Labels: javascript, python
