Repository mozilla/treeherder, pull requests merged in 2019-08, with the labels that each got.

#5091 Bug 1553734 - Quickly copy full commit hash
  ui/css/treeherder-resultsets.css
  ui/job-view/pushes/Revision.jsx
Labels: javascript

#4954 Bug 1346567 - cycle_data is failing on stage/production
  tests/conftest.py
  tests/model/test_cycle_data.py
  treeherder/model/management/commands/cycle_data.py
  treeherder/perf/exceptions.py
  treeherder/perf/models.py
Labels: python

#5228 Bug 1553719 - Trim revision id for compare chooser
  tests/ui/perfherder/selector_card_test.jsx
  ui/perfherder/compare/SelectorCard.jsx
  ui/perfherder/constants.js
Labels: javascript

#5243 Switch from `jest-dom` to `@testing-library/jest-dom`
  package.json
  tests/ui/test-setup.js
  yarn.lock
Labels: dependencies, javascript

#5092 Bug 1470599 - Compare result against another revision should take you to the right framework
  ui/perfherder/compare/CompareSelectorView.jsx
Labels: javascript

#5301 Bug 1524521 - Provisioning local perf data is hard
  treeherder/perf/management/commands/import_perf_data.py
Labels: python
