Repository mozilla/treeherder, pull requests merged in 2019-10, with the labels that each got.

#5296 Bug 1571404 - Self assign/unassign from alert summaries
  tests/ui/perfherder/alerts_test.jsx
  ui/perfherder/alerts/AlertHeader.jsx
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
  ui/perfherder/alerts/Assignee.jsx
  ui/perfherder/alerts/StatusDropdown.jsx
  ui/perfherder/helpers.js
Labels: javascript, python

#5365 Bug 1571409 - Add a "My alert summaries" checkbox on Alerts view
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
Labels: javascript

#5411 Bug 1584934 - Provide backend support for measurement units
  treeherder/perf/migrations/0018_add_measurement_units.py
  treeherder/perf/models.py
  treeherder/webapp/api/performance_serializers.py
Labels: db-schema-changes, python

#5419 Ingest measurement units
  tests/etl/conftest.py
  tests/etl/test_perf_data_adapters.py
  tests/etl/test_perf_data_load.py
  treeherder/etl/perf.py
Labels: python

#5388 Bug 1582108 - Completely remove confirming state
  tests/webapp/api/test_performance_alerts_api.py
  treeherder/perf/migrations/0018_remove_confirming_state.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#5478 Bug 1580687 - Provide backend endpoint for test validity dashboard
  treeherder/webapp/api/performance_data.py
  treeherder/webapp/api/performance_serializers.py
  treeherder/webapp/api/urls.py
  treeherder/webapp/api/utils.py
Labels: python

#5511 Bug 1582108 - Completely remove confirming state
  tests/webapp/api/test_performance_alerts_api.py
  treeherder/perf/migrations/0019_remove_confirming_state.py
  treeherder/perf/models.py
Labels: db-schema-changes, python
