Repository mozilla/treeherder, pull requests merged in 2020-03, with the labels that each got.

#6088 Bug 1618827 - Create basic config for perfSheriffBot
  treeherder/config/settings.py
Labels: python

#6086 Bug 1618820 - Include reporter tool logic in the PerfSheriffBot
  treeherder/perf/management/commands/synthesize_backfill_report.py
  treeherder/perf/perf_sheriff_bot.py
Labels: python

#6036 Bug 1615535 Changing alert's status/assignee changes page's content
  ui/perfherder/alerts/AlertsView.jsx
Labels: javascript

#6087 Bug 1618811 - Add columns for the status and details
  treeherder/perf/migrations/0026_add_backfill_record_status.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#6098 Bug 1618846 - Grab variables via Django’s settings.py
  docker-compose.yml
  treeherder/config/settings.py
Labels: python

#6121 Bug 1618812 - Define table for storing the daily limits
  treeherder/perf/migrations/0027_support_perfherder_settings.py
  treeherder/perf/models.py
Labels: db-schema-changes

#6070 Bug 1509181 - Github ingestion: Ingest pushes in the right order
  docker-compose.yml
  docs/installation.md
  tests/sample_data/pulse_consumer/transformed_gh_pr.json
  treeherder/config/settings.py
  treeherder/etl/common.py
  treeherder/etl/management/commands/ingest.py
  treeherder/etl/push_loader.py
  treeherder/utils/github.py
Labels: python

#6066 Bug 1618145 Tooltip revision link directs to empty pushlog
  ui/perfherder/graphs/GraphTooltip.jsx
Labels: javascript

#6120 Bug 1615330 - Support filtering by test paths rather than manifest paths
  tests/ui/helpers/gzip_test.js
  tests/ui/job-view/Push_test.jsx
  ui/helpers/gzip.js
  ui/job-view/pushes/Push.jsx
  ui/models/filter.js
Labels: javascript

#6056 Bug 1618889 - Remove reduntant graph view test from selenium
  tests/selenium/test_perfherder.py
  tests/ui/perfherder/graphs_view_test.jsx
  ui/perfherder/graphs/GraphTooltip.jsx
Labels: javascript, python

#6172 Bug 1615330 - Support test filtering instead of manifest filtering
  tests/ui/helpers/gzip_test.js
  tests/ui/job-view/Push_test.jsx
  ui/helpers/gzip.js
  ui/job-view/pushes/Push.jsx
  ui/models/filter.js
Labels: javascript

#6175 Do not initialize data if DATABASE_URL is set
  initialize_data.sh
Labels: docker

#6151 Bug 1618837 - PerfSheriffBot-should-condition-the-backfill-by-the-query-load-of-queue
  treeherder/perf/perf_sheriff_bot.py
Labels: python

#6189 Bug 1618521 - Push Health no test name ellipses
  treeherder/push_health/utils.py
  ui/push-health/GroupedTests.jsx
Labels: javascript
