Repository mozilla/treeherder, pull requests merged in 2020-07, with the labels that each got.

#6557 Bug 1648688 - Add 'improvement' tag to performance tags
  treeherder/perf/fixtures/performance_tag.yaml
  ui/perfherder/constants.js
Labels: db-schema-changes, javascript, python

#6548 Bug 1646343 - Provide test coverage for performance tags
  tests/ui/mock/performance_tags.json
  tests/ui/perfherder/alerts-view/alerts_test.jsx
  tests/ui/perfherder/alerts-view/modal_perf_tags_test.jsx
  tests/ui/perfherder/alerts-view/status_dropdown_test.jsx
  ui/perfherder/alerts/TagsModal.jsx
Labels: javascript

#6575 Bug 1633041 - Add Job to TextLogError and create backfill command
  newrelic.ini
  tests/e2e/test_job_ingestion.py
  tests/etl/test_job_loader.py
  tests/extract/conftest.py
  tests/extract/test_extract_job.json
  tests/extract/test_extract_job.sql
  tests/sample_data/job_data.txt
  tests/sample_data/pulse_consumer/job_data.json
  tests/sample_data/pulse_consumer/taskcluster_transformed_jobs.json
  tests/sample_data/pulse_consumer/transformed_job_data.json
  tests/webapp/api/test_jobs_api.py
  tests/webapp/api/test_text_log_error.py
  treeherder/etl/artifact.py
  treeherder/etl/jobs.py
  treeherder/etl/taskcluster_pulse/handler.py
  treeherder/log_parser/tasks.py
  treeherder/model/management/commands/backfill_text_log_error_jobs.py
  treeherder/model/migrations/0020_textlogerror_job.py
  treeherder/model/models.py
  treeherder/webapp/api/text_log_error.py
  treeherder/webapp/api/urls.py
  ui/logviewer/App.jsx
Labels: python

#6591 Bug 1651299 - Find workaround for usual fullstack mode
  package.json
Labels: javascript

#6596 Bug 1649229 - Filter backfilled manifest scheduled tasks
  tests/ui/job-view/Filtering_test.jsx
  ui/helpers/job.js
Labels: javascript

#6599 Bug 1644851 - Fix Failure Summary scroll and selection on job change
  ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Labels: javascript

#6625 Bug 1649229 - Also make backfill tasks match the same search string
  ui/helpers/job.js
Labels: javascript

#6547 Bug 1649387 - Provide enhanced management script for Bugzilla formulas
  .gitignore
  tests/perf/test_sheriffing_criteria/test_criteria_tracker.py
  tests/sample_data/criteria-records.csv
  treeherder/perf/management/commands/compute_criteria_formulas.py
  treeherder/perf/sheriffing_criteria/__init__.py
  treeherder/perf/sheriffing_criteria/bugzilla_formulas.py
  treeherder/perf/sheriffing_criteria/criteria_tracking.py
  treeherder/utils/__init__.py
Labels: python

#6629 Bug 1644269 - Unable to add results for the same test but different apps
  tests/ui/perfherder/graphs_view_test.jsx
  tests/webapp/api/test_performance_data_api.py
  treeherder/webapp/api/performance_data.py
  ui/models/perfSeries.js
Labels: javascript, python

#6636 Issue 6630 - Add Test Groups tab
  tests/ui/job-view/Filtering_test.jsx
  tests/ui/job-view/details/PinBoard_test.jsx
  tests/ui/mock/task_definition.json
  ui/css/treeherder-details-panel.css
  ui/job-view/details/DetailsPanel.jsx
  ui/job-view/details/JobTestGroups.jsx
  ui/job-view/details/summary/ActionBar.jsx
  ui/job-view/details/tabs/TabsPanel.jsx
  ui/logviewer/App.jsx
  ui/shared/JobArtifacts.jsx
Labels: javascript

#6652 Bug 1576966 - Rewrite selected-job Selenium tests in React Testing Lib
  tests/selenium/test_info_panel.py
  tests/selenium/test_select_job.py
  tests/selenium/test_select_unclassified_job.py
  tests/ui/job-view/App_test.jsx
  tests/ui/job-view/Filtering_test.jsx
  tests/ui/job-view/details/PinBoard_test.jsx
  tests/ui/job-view/stores/pushes_test.jsx
  tests/ui/mock/job_list/job_1.json
  ui/job-view/details/summary/SummaryPanel.jsx
Labels: javascript

#6653 Bug 1638424 - Translate WPT paths in the test path filter
  tests/ui/job-view/Push_test.jsx
  ui/job-view/pushes/Push.jsx
Labels: javascript

#6668 Selenium test: Skip test_open_log_viewer
  tests/selenium/test_log_viewer.py
Labels: python

#6666 Refactor ingestion code & store push when ingesting task
  treeherder/etl/management/commands/ingest.py
Labels: python

#6594 Bug 1651374 - Display tags for tests
  tests/ui/mock/alert_summaries.json
  tests/ui/mock/performance_signature_with_no_tags.json
  tests/ui/mock/performance_signature_with_repeated_tag.json
  tests/ui/perfherder/alerts-view/alerts_table_row_test.jsx
  tests/ui/perfherder/graphs-view/graphs_view_test.jsx
  tests/ui/perfherder/graphs-view/test_data_model_test.jsx
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertTableRow.jsx
  ui/perfherder/graphs/GraphsContainer.jsx
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript

#6669 Bug 1656036 - Stop trying to ingest Fenix pushes for branches that we…
  treeherder/etl/job_loader.py
  treeherder/etl/taskcluster_pulse/handler.py
Labels: python

#6672 Bug 1656036 - Polish logic to ignore ingestion of tasks
  tests/etl/test_job_loader.py
  treeherder/etl/job_loader.py
  treeherder/etl/taskcluster_pulse/handler.py
Labels: python
