Repository mozilla/treeherder, pull requests merged in 2020-06, with the labels that each got.

#6367 Skip ingestion when DATABASE_URL points to remote host
  treeherder/config/settings.py
  treeherder/etl/management/commands/pulse_listener.py
  treeherder/etl/management/commands/pulse_listener_pushes.py
  treeherder/etl/management/commands/pulse_listener_tasks.py
Labels: docker, python

#6509 Bug 1644347 - Perfhderder: Add new test modal - order alphabetically the platforms dropdown
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript

#6473 Bug 1639136 - Endpoints related to alert summaries should retrieve performance tags
  tests/conftest.py
  tests/webapp/api/test_performance_alertsummary_api.py
  treeherder/model/management/commands/load_initial_data.py
  treeherder/webapp/api/performance_data.py
  treeherder/webapp/api/performance_serializers.py
Labels: db-schema-changes, python

#6510 Bug 1644350 - Provide read endpoint for performance tags
  tests/webapp/api/test_performance_tags.py
  treeherder/webapp/api/performance_data.py
  treeherder/webapp/api/urls.py
Labels: python

#6458 Bug 1642554 - Implement model for engineer traction formula
  .gitignore
  requirements/dev.in
  requirements/dev.txt
  tests/README.md
  tests/perf/__init__.py
  tests/perf/test_engineer_traction.py
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/awsy-JS.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/build_metrics-build times.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/build_metrics-installer size.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/cooled-down-bug-history.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/nonexistent_framework-nonexistent_suite.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/quantified-bugs.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/raptor-raptor-speedometer-firefox.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/raptor-raptor-webaudio-firefox.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5n-nonmain_startup_fileio.json
  treeherder/config/settings.py
  treeherder/perf/exceptions.py
  treeherder/perf/sheriffing_criteria.py
Labels: python

#6520 Bug 1645490 - Add mozilla-esr78 and placeholder comm-esr78.
  treeherder/model/fixtures/repository.json
  ui/intermittent-failures/constants.js
Labels: javascript

#6526 Security update for Django
  requirements/common.in
  requirements/common.txt
  requirements/dev.in
  requirements/dev.txt
Labels: dependencies, python, security

#6392 Bug 1601730 - Move KeyboardShortcuts to react-hot-keys
  package.json
  tests/ui/job-view/Filtering_test.jsx
  tests/ui/job-view/details/PinBoard_test.jsx
  ui/job-view/KeyboardShortcuts.jsx
  yarn.lock
Labels: javascript

#6523 Bug 1644433 - Implement UI/UX decisions
  tests/ui/mock/alert_summaries.json
  tests/ui/mock/performance_tags.json
  tests/ui/perfherder/alerts_test.jsx
  ui/perfherder/App.jsx
  ui/perfherder/alerts/AlertHeader.jsx
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertsView.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
  ui/perfherder/alerts/StatusDropdown.jsx
  ui/perfherder/alerts/TagsList.jsx
  ui/perfherder/alerts/TagsModal.jsx
  ui/perfherder/constants.js
Labels: javascript

#6493 Bug 1643667 - Fix ratio implementation
  tests/perf/test_engineer_traction.py
  tests/perf/test_sheriffing_criteria/__init__.py
  tests/perf/test_sheriffing_criteria/conftest.py
  tests/perf/test_sheriffing_criteria/test_common_behaviour.py
  tests/perf/test_sheriffing_criteria/test_engineer_traction.py
  tests/perf/test_sheriffing_criteria/test_fix_ratio.py
  tests/perf/test_sheriffing_criteria/test_nonblockable_session.py
  treeherder/perf/sheriffing_criteria.py
Labels: python

#6551 Security fixes
  package.json
  yarn.lock
Labels: dependencies, javascript, security

#6553 Update serialize-javascript to handle security issue
  package.json
  yarn.lock
Labels: dependencies, javascript, security

#6495 Bug 1643709 - Provide basic management script for Bugzilla formulas
  treeherder/perf/management/commands/compute_criteria_formulas.py
Labels: python

#6562 Bug 1649289 - Fix Push Health commit order
  treeherder/push_health/compare.py
Labels: javascript

#6092 Bug 1616759 - Provide test coverage for grouping of common repositories
  tests/ui/perfherder/dropdown_menu_test.jsx
Labels: javascript

#6531 Push health details tabs
  tests/ui/mock/full_job.json
  tests/ui/push-health/ClassificationGroup_test.jsx
  tests/ui/push-health/Job_test.jsx
  tests/ui/push-health/TestFailure_test.jsx
  treeherder/push_health/similar_jobs.py
  ui/css/failure-summary.css
  ui/css/lazylog-custom-styles.css
  ui/css/treeherder-details-panel.css
  ui/helpers/display.js
  ui/job-view/details/DetailsPanel.jsx
  ui/job-view/details/tabs/TabsPanel.jsx
  ui/job-view/index.jsx
  ui/logviewer/App.jsx
  ui/logviewer/index.jsx
  ui/logviewer/logviewer.css
  ui/push-health/ClassificationGroup.jsx
  ui/push-health/TestFailure.jsx
  ui/push-health/details/DetailsPanel.jsx
  ui/push-health/helpers.js
  ui/push-health/index.jsx
  ui/push-health/pushhealth.css
  ui/shared/NotificationList.jsx
  ui/shared/tabs/LogviewerTab.jsx
  ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Labels: javascript
