Repository mozilla/treeherder, pull requests merged in 2020-05, with the labels that each got.

#6351 Bug 1593815 - Perfherder doesn't reload if you change the URL
  ui/perfherder/compare/CompareTableView.jsx
Labels: javascript

#6356 Bug 1631082 - Fix alerts extraction to bigquery
  requirements/common.txt
  tests/extract/test_extract_alerts.sql
  treeherder/extract/extract_alerts.json
Labels: python

#6013 Bug 1615227 - AlertsView: Add first last to pagination
  ui/perfherder/alerts/AlertsViewControls.jsx
  ui/perfherder/alerts/Pagination.jsx
Labels: javascript

#6387 Upgrade React Testing Library and React
  .travis.yml
  package.json
  tests/ui/job-view/App_test.jsx
  tests/ui/job-view/Filtering_test.jsx
  tests/ui/job-view/PushList_test.jsx
  tests/ui/job-view/Push_test.jsx
  tests/ui/job-view/SecondaryNavBar_test.jsx
  tests/ui/job-view/details/PinBoard_test.jsx
  tests/ui/job-view/revisions_test.jsx
  tests/ui/job-view/selected_job_test.jsx
  tests/ui/job-view/stores/selectedJob_test.jsx
  tests/ui/perfherder/alerts_test.jsx
  tests/ui/perfherder/compare_table_test.jsx
  tests/ui/perfherder/graphs_view_test.jsx
  tests/ui/perfherder/legend_card_test.jsx
  tests/ui/perfherder/replicates_graph_test.jsx
  tests/ui/perfherder/retrigger_modal_test.jsx
  tests/ui/perfherder/selector_card_test.jsx
  tests/ui/perfherder/tests_table_test.jsx
  tests/ui/push-health/CommitHistory_test.jsx
  tests/ui/push-health/GroupedTests_test.jsx
  tests/ui/push-health/Health_test.jsx
  tests/ui/push-health/JobListMetric_test.jsx
  tests/ui/push-health/Job_test.jsx
  tests/ui/push-health/TestFailure_test.jsx
  tests/ui/push-health/UnsupportedJob_test.jsx
  tests/ui/push-health/Usage_test.jsx
  yarn.lock
Labels: dependencies, effort: medium, javascript

#6407 Upgrade Neutrino from 9.0.0 to 9.1.0
  package.json
  yarn.lock
Labels: dependencies, javascript

#6408 Reduce logging
  treeherder/etl/perf.py
  treeherder/etl/pushlog.py
  treeherder/etl/taskcluster_pulse/handler.py
  treeherder/push_health/tests.py
Labels: python

#6368 Bug 1632403 Graph View - Refresh results in add new test modal when changing dropdowns
  tests/ui/mock/performance_signature_formatted2.json
  tests/ui/perfherder/graphs_view_test.jsx
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript

#6411 Bug 1626746 - Push Health use Mozci to get Push parent
  requirements/common.in
  requirements/common.txt
  tests/push_health/test_compare.py
  treeherder/config/settings.py
  treeherder/push_health/compare.py
Labels: python

#6302 Bug 1618836 - Integrate the backfill logic in the PerfSheriffBot
  tests/conftest.py
  tests/perfalert/test_alerts/test_secretary_tool.py
  tests/perfalert/test_perf_sheriff_bot.py
  tests/sample_data/perf_sheriff_bot/recordContext.json
  tests/services/test_taskcluster.py
  treeherder/perf/alerts.py
  treeherder/perf/management/commands/synthesize_backfill_report.py
  treeherder/perf/models.py
  treeherder/perf/perf_sheriff_bot.py
  treeherder/perf/secretary_tool.py
  treeherder/utils/__init__.py
Labels: python

#6417 Bug 1637526 Show tooltip information properly when some of them are missing
  ui/perfherder/graphs/GraphTooltip.jsx
Labels: javascript

#6373 Bug 1615540 - Remove AWFY from Perfherder
  treeherder/perf/fixtures/performance_framework.json
  treeherder/webapp/api/performance_data.py
Labels: python

#6152 Bug 1618578 - All perfherder dropdowns have the items in alphabetical order
  ui/perfherder/graphs/TestDataModal.jsx
  ui/shared/DropdownMenuItems.jsx
Labels: javascript

#6450 Bug 1587145 - Upgrade taskcluster-client-web to v30
  package.json
  yarn.lock
Labels: dependencies

#6434 Bug 1639127 - Provide required ORM model for performance tags
  tests/conftest.py
  tests/extract/test_extract_alerts.sql
  tests/model/test_performance_tag.py
  treeherder/perf/fixtures/performance_tag.yaml
  treeherder/perf/migrations/0032_add_performance_tag.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#6462 fixed misspelling of sheriff
  treeherder/perf/secretary_tool.py
Labels: python
