Repository mozilla/treeherder, pull requests merged in 2020-04, with the labels that each got.

#6204 Bug 1625450 - Default application field to unspecified or empty string
  treeherder/etl/perf.py
Labels: python

#6213 Bug 1625451 - Provide default for application field
  treeherder/perf/migrations/0028_default_application_to_empty_str.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#6157 Bug 1618840 - Create secretary tool for PerfSheriffBot
  tests/perfalert/test_alerts/test_secretary_tool.py
  treeherder/perf/alerts.py
  treeherder/perf/migrations/0029_add_frozen_to_report.py
  treeherder/perf/models.py
  treeherder/perf/secretary_tool.py
Labels: db-schema-changes, python

#6214 Bug 1625454 - Signature unique constraint should include application field
  treeherder/perf/migrations/0030_add_application_to_contraints.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#6141 Slimmer requirements
  requirements/common.in
  requirements/common.txt
  requirements/dev.in
  requirements/dev.txt
  setup.cfg
  tests/README.md
  treeherder/etl/jobs.py
Labels: dependencies, python

#6275 Bug 1627265 - At data ingestion distinguish between firefox and chrome applications
  treeherder/etl/perf.py
Labels: python

#6278 Bug 1627968 - Rename Health view to Tests view
  tests/ui/perfherder/tests_table_test.jsx
  ui/perfherder/App.jsx
  ui/perfherder/Navigation.jsx
  ui/perfherder/tests/ItemList.jsx
  ui/perfherder/tests/TestsTable.jsx
  ui/perfherder/tests/TestsTableControls.jsx
  ui/perfherder/tests/TestsView.jsx
Labels: javascript

#6295 Bug 1629139 - Update Pulse Docs and allow skip of ingestion
  docker-compose.yml
  docs/installation.md
  docs/pulseload.md
  treeherder/etl/management/commands/pulse_listener_pushes.py
  treeherder/etl/management/commands/pulse_listener_tasks.py
Labels: docker, python

#6155 Bug 1595111 – Alerts view gets stuck on last page
  ui/perfherder/alerts/AlertsViewControls.jsx
Labels: javascript

#6301 Bug 1628991 - Span children are missing "key" prop
  ui/perfherder/tests/ItemList.jsx
Labels: javascript

#6037 Bug 1612547 - Define component for doing backfills using existing reports
  requirements/common.txt
  tests/perfalert/conftest.py
  tests/perfalert/test_backfill_tool.py
  tests/sample_data/perf_sheriff_bot/backfilltask.json
  tests/sample_data/perf_sheriff_bot/initialActions.json
  tests/sample_data/perf_sheriff_bot/matchingTagSetList.json
  tests/sample_data/perf_sheriff_bot/matchingTaskTags.json
  tests/sample_data/perf_sheriff_bot/mismatchingTagSetList.json
  tests/sample_data/perf_sheriff_bot/mismatchingTaskTags.json
  tests/sample_data/perf_sheriff_bot/originalTask.json
  tests/sample_data/perf_sheriff_bot/reducedActions.json
  tests/services/test_taskcluster.py
  tests/utils/test_taskcluster_lib_scopes.py
  treeherder/model/models.py
  treeherder/perf/backfill_tool.py
  treeherder/perf/exceptions.py
  treeherder/perf/management/commands/backfill_perf_jobs.py
  treeherder/services/taskcluster.py
  treeherder/utils/taskcluster_lib_scopes.py
Labels: python

#6314 Bug 1630712 - Single try push view show Push Health Summary
  treeherder/webapp/api/push.py
  ui/css/intermittent-failures.css
  ui/css/treeherder-custom-styles.css
  ui/job-view/pushes/Push.jsx
  ui/job-view/pushes/PushHeader.jsx
  ui/shared/PushHealthStatus.jsx
  ui/shared/PushHealthSummary.jsx
  ui/shared/RevisionList.jsx
Labels: effort: medium, javascript

#6177 Bug 1605352 - Add Performance FAQ to reference to regression template
  treeherder/perf/fixtures/performance_bug_templates.yaml
  ui/perfherder/alerts/StatusDropdown.jsx
Labels: javascript

#6300 Bug 1616215 - Warn when user filters by option or repository
  tests/ui/mock/alert_summaries.json
  tests/ui/perfherder/alerts_test.jsx
  ui/perfherder/alerts/AlertsView.jsx
  ui/perfherder/constants.js
Labels: javascript

#6338 Document Tox as a requirement for running tests
  .gitignore
  docs/testing.md
Labels: python

#6346 Bug 1630293 - Increase max connections for Docker set up
  docker/mysql.cnf
Labels: docker

#6340 Bug 1630714 - No perfherder data displayed for some jobs
  tests/model/test_performance_signature.py
  treeherder/etl/perf.py
  treeherder/perf/migrations/0031_fix_application_in_constraints.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#6336 Bug 1632074 Replace framework ID with framework name in regression te…
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/StatusDropdown.jsx
Labels: javascript

#6371 Bug 1632946 - Remove signature link for filtering in the UI
  tests/ui/job-view/Filtering_test.jsx
  ui/helpers/job.js
  ui/logviewer/App.jsx
  ui/shared/JobInfo.jsx
Labels: javascript
