Repository mozilla/treeherder, pull requests merged in 2020-10, with the labels that each got.

#6710 Bug 1654496 - Update perfherder to ingest and present test information generated by multi commit builds
  tests/etl/test_perf_data_load.py
  treeherder/etl/perf.py
  treeherder/perf/management/commands/remove_multi_commit_data.py
  treeherder/perf/migrations/0033_permit_multi_data_per_job.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#6792 Bug 1669416 - Improve wording of Perfherder Bugzilla message
  ui/perfherder/helpers.js
Labels: javascript

#6788 Add more prominent buttons to the PerformanceTab
  ui/css/treeherder-custom-styles.css
  ui/css/treeherder-details-panel.css
  ui/helpers/performance.js
  ui/job-view/details/DetailsPanel.jsx
  ui/job-view/details/summary/ActionBar.jsx
  ui/job-view/details/tabs/PerformanceTab.jsx
  ui/job-view/details/tabs/TabsPanel.jsx
Labels: javascript

#6780 Bug 1667051 - Remove `try` perf data older than 6 weeks
  tests/conftest.py
  tests/model/test_cycle_data.py
  treeherder/model/management/commands/cycle_data.py
  treeherder/perf/exceptions.py
  treeherder/perf/models.py
Labels: python

#6816 Bug 1671893 - Convert int timestamp to datetime
  tests/etl/test_perf_data_load.py
  treeherder/etl/perf.py
Labels: python

#6786 Bug 1668511 - Remove empty summaries
  tests/model/test_cycle_data.py
  treeherder/model/management/commands/cycle_data.py
Labels: python

#6828 Bug 1668511 - Remove empty alert summaries v2
  tests/model/test_cycle_data.py
  treeherder/model/management/commands/cycle_data.py
Labels: python

#6801 Bug 1550014 - Allow sorting by table column on compare subtest page
  tests/ui/perfherder/compare-view/compare_table_test.jsx
  ui/perfherder/compare/CompareSortButton.jsx
  ui/perfherder/compare/CompareTable.jsx
  ui/perfherder/constants.js
Labels: javascript

#6832 Bug 1669490 - Faster expiry for data from irrelevant repos
  tests/conftest.py
  tests/model/test_cycle_data.py
  treeherder/model/management/commands/cycle_data.py
Labels: python
