Repository mozilla/treeherder, pull requests merged in 2020-08, with the labels that each got.

#6689 Taskcluster utils module
  treeherder/etl/job_loader.py
  treeherder/utils/taskcluster.py
Labels: python

#6697 Fix: Ingest mobile nightly tasks
  treeherder/etl/management/commands/ingest.py
  treeherder/etl/taskcluster_pulse/handler.py
Labels: python

#6694 Bug 1626623 - Faster test path filtering (drop filtering by test file)
  tests/ui/job-view/Push_test.jsx
  ui/job-view/pushes/Push.jsx
Labels: javascript

#6650 Bug 1634263 - Alerts view's text search doesn't filter related alerts
  tests/webapp/api/test_performance_alertsummary_api.py
  treeherder/webapp/api/performance_data.py
Labels: python

#6712 Bug 1658922 - Display application name in Graphs view modal
  tests/ui/perfherder/graphs-view/graphs_view_test.jsx
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript

#6686 Bug 1656428 - Tests can be filtered with multiple tags
  tests/ui/perfherder/graphs-view/graphs_view_test.jsx
  tests/ui/perfherder/graphs-view/test_data_modal_test.jsx
  tests/ui/perfherder/graphs-view/test_data_model_test.jsx
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript

#6476 Local dev: Skip ingesting if pointing to an RDS DB
  docker-compose.yml
  treeherder/config/settings.py
  treeherder/etl/management/commands/pulse_listener_pushes.py
  treeherder/etl/management/commands/pulse_listener_tasks.py
Labels: docker, python

#6720 Bug 1659656 - Provide subtest granularity
  tests/perf/test_sheriffing_criteria/test_criteria_tracker.py
  tests/perf/test_sheriffing_criteria/test_engineer_traction.py
  tests/perf/test_sheriffing_criteria/test_fix_ratio.py
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/raptor-raptor-tp6-google-mail-firefox-cold.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5n-nonmain_startup_fileio.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5n.json
  tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5o.json
  tests/sample_data/criteria-records.csv
  treeherder/perf/management/commands/compute_criteria_formulas.py
  treeherder/perf/sheriffing_criteria/bugzilla_formulas.py
  treeherder/perf/sheriffing_criteria/criteria_tracking.py
Labels: python
