Repository mozilla/treeherder, pull requests merged in 2020-02, with the labels that each got.

#5896 Bug 1609359 - Provide framework name in alert summary headers
  tests/ui/perfherder/alerts_test.jsx
  tests/ui/perfherder/legend_card_test.jsx
  ui/perfherder/alerts/AlertHeader.jsx
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/constants.js
  ui/perfherder/graphs/LegendCard.jsx
  ui/perfherder/helpers.js
Labels: javascript

#5925 Bug 1612892 - Perfherder's Health view is broken
  ui/helpers/url.js
  ui/perfherder/constants.js
  ui/perfherder/health/HealthView.jsx
Labels: javascript

#5939 Bug 1613344 - Dropdowns are broken
  ui/shared/DropdownMenuItems.jsx
Labels: javascript

#5902 Bug 1612224 - Give access to parent of Push Health commit
  tests/push_health/test_compare.py
  tests/ui/push-health/PushParent_test.jsx
  treeherder/model/migrations/0016_add_index_commit_revision.py
  treeherder/model/models.py
  treeherder/push_health/compare.py
  treeherder/webapp/api/push.py
  ui/push-health/Health.jsx
  ui/push-health/PushParent.jsx
  ui/push-health/helpers.js
  ui/shared/PushHealthStatus.jsx
Labels: db-schema-changes, javascript

#5835 Bug 1609081 - Provide full server side search in Alerts view
  tests/ui/mock/alert_summaries.json
  tests/ui/perfherder/alerts_test.jsx
  treeherder/webapp/api/performance_data.py
  ui/perfherder/App.jsx
  ui/perfherder/FilterControls.jsx
  ui/perfherder/Validation.jsx
  ui/perfherder/alerts/AlertsView.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
  ui/shared/InputFilter.jsx
Labels: javascript, python

#5946 Add a quick link to compare a given revision in perfherder.
  ui/job-view/pushes/PushActionMenu.jsx
Labels: javascript

#5997 Bug 1614581 - Remove related mozilla-inbound series when clicking through from Alerts view
  ui/perfherder/helpers.js
Labels: javascript

#6063 Switch some info messages to debug
  treeherder/autoclassify/tasks.py
  treeherder/etl/push_loader.py
  treeherder/services/pulse/consumers.py
Labels: python

#6043 Bug 1614578 - Differentiate the "all" items from status & framework dropdowns
  tests/ui/perfherder/alerts_test.jsx
  ui/perfherder/alerts/AlertsView.jsx
  ui/perfherder/constants.js
Labels: javascript
