Repository mozilla/treeherder, pull requests merged in 2020-01, with the labels that each got.

#5742 Display revision comments in RevisionInformation.
  ui/css/perf.css
  ui/perfherder/compare/RevisionInformation.jsx
Labels: javascript

#5735 Bug 1587404 - Integrate tags into all filter text inputs, so they're easily searcheable
  tests/conftest.py
  tests/ui/mock/performance_signature_formatted.json
  tests/ui/perfherder/graphs_view_test.jsx
  tests/webapp/api/test_performance_data_api.py
  treeherder/webapp/api/performance_data.py
  treeherder/webapp/api/performance_serializers.py
  ui/models/perfSeries.js
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript, python

#5799 Manual ingestion improvements
  docs/installation.md
  treeherder/etl/management/commands/ingest.py
Labels: python

#5599 Bug 1584947 - Display measurement units on the Graphs view
  tests/conftest.py
  tests/ui/mock/performance_signature_formatted.json
  tests/ui/perfherder/graphs_view_test.jsx
  tests/webapp/api/test_performance_data_api.py
  treeherder/webapp/api/performance_data.py
  treeherder/webapp/api/performance_serializers.py
  ui/models/perfSeries.js
  ui/perfherder/graphs/GraphTooltip.jsx
  ui/perfherder/graphs/GraphsContainer.jsx
  ui/perfherder/graphs/GraphsView.jsx
  ui/perfherder/graphs/GraphsViewControls.jsx
  ui/perfherder/graphs/TestDataModal.jsx
Labels: javascript, python

#5740 Bug 1603084 - import_perf_data does not know how to import BackfillRecord and BackfillRecord
  docker-compose.yml
  treeherder/perf/management/commands/import_perf_data.py
Labels: python

#5547 Bug 1569584 - retriggering dialog on compare view
  .neutrinorc.js
  tests/ui/perfherder/compare_table_test.jsx
  tests/ui/perfherder/retrigger_modal_test.jsx
  ui/perfherder/compare/ComparePageTitle.jsx
  ui/perfherder/compare/CompareTable.jsx
  ui/perfherder/compare/CompareTableControls.jsx
  ui/perfherder/compare/CompareTableRow.jsx
  ui/perfherder/compare/RetriggerButton.jsx
  ui/perfherder/compare/RetriggerModal.jsx
  ui/perfherder/constants.js
  ui/perfherder/helpers.js
Labels: javascript

#5687 Bug 1593198 - Surface the application name in Graphs view
  tests/conftest.py
  tests/ui/mock/performance_signature_formatted.json
  tests/ui/perfherder/graphs_view_test.jsx
  tests/ui/perfherder/legend_card_test.jsx
  tests/webapp/api/test_performance_data_api.py
  treeherder/webapp/api/performance_data.py
  treeherder/webapp/api/performance_serializers.py
  ui/helpers/url.js
  ui/models/perfSeries.js
  ui/perfherder/compare/CompareSubtestDistributionView.jsx
  ui/perfherder/compare/CompareTableView.jsx
  ui/perfherder/compare/ReplicatesGraph.jsx
  ui/perfherder/constants.js
  ui/perfherder/graphs/GraphsView.jsx
  ui/perfherder/graphs/LegendCard.jsx
  ui/perfherder/graphs/TestDataModal.jsx
  ui/perfherder/helpers.js
Labels: javascript, python

#5819 Bug 1609059 - Remove My alerts in detailed Alerts view
  tests/ui/perfherder/alerts_test.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
Labels: javascript

#5848 Bug 1609079 - Add “all” item to framework dropdown
  tests/ui/perfherder/alerts_test.jsx
  ui/perfherder/App.jsx
  ui/perfherder/FilterControls.jsx
  ui/perfherder/alerts/AlertsView.jsx
  ui/shared/DropdownMenuItems.jsx
Labels: javascript
