Repository mozilla/treeherder, pull requests merged in 2021-04, with the labels that each got.

#7077 Bug 1700946 - Record status change
  treeherder/perf/migrations/0038_update_record_status.py
  treeherder/perf/models.py
Labels: db-schema-changes

#7061 Bug 1697108- Move TIME_TO_MATURE constant from secretery_tool.py to s…
  treeherder/config/settings.py
  treeherder/perf/auto_perf_sheriffing/secretary_tool.py
Labels: python

#7080 Bug 1702410 - Reflect backfill bot' s new name in logs
  schemas/perf-sheriff-bot-log-details.json
  tests/perf/auto_perf_sheriffing/__init__.py
  tests/perf/auto_perf_sheriffing/conftest.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/__init__.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/conftest.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_alerts_picker.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_backfill_report_maintainer.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_identify_retriggerables.py
  tests/perf/auto_perf_sheriffing/test_backfill_tool.py
  tests/perf/auto_perf_sheriffing/test_secretary.py
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  tests/perf/auto_sheriffing_criteria/conftest.py
  tests/perfalert/conftest.py
  tests/sample_data/sherlock/backfillTask.json
  tests/sample_data/sherlock/initialActions.json
  tests/sample_data/sherlock/matchingTagSetList.json
  tests/sample_data/sherlock/matchingTaskTags.json
  tests/sample_data/sherlock/mismatchingTagSetList.json
  tests/sample_data/sherlock/mismatchingTaskTags.json
  tests/sample_data/sherlock/originalTask.json
  tests/sample_data/sherlock/recordContext.json
  tests/sample_data/sherlock/reducedActions.json
  tests/services/test_taskcluster.py
  treeherder/config/settings.py
  treeherder/perf/auto_perf_sherrifing/__init__.py
  treeherder/perf/auto_perf_sherrifing/backfill_reports.py
  treeherder/perf/auto_perf_sherrifing/backfill_tool.py
  treeherder/perf/auto_perf_sherrifing/factories.py
  treeherder/perf/auto_perf_sherrifing/outcome_checker.py
  treeherder/perf/auto_perf_sherrifing/secretary.py
  treeherder/perf/auto_perf_sherrifing/sherlock.py
  treeherder/perf/management/commands/backfill_perf_jobs.py
  treeherder/perf/management/commands/perf_sheriff.py
  treeherder/perf/models.py
Labels: python

#7090 Bug 1703024 - More debug logs for Sherlock' s email notification
  treeherder/perf/auto_perf_sherrifing/sherlock.py
Labels: python

#7085 Bug 1702720 - Fix email formatting
  docker-compose.yml
  treeherder/perf/email.py
Labels: docker, python

#7081 Bug 1618829 - Fully enable PerfSheriffBot
  tests/conftest.py
  tests/model/cycle_data/test_perfherder_cycling.py
  tests/perf/auto_perf_sheriffing/conftest.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/conftest.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_alerts_picker.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_backfill_report_maintainer.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_identify_retriggerables.py
  tests/perf/auto_perf_sheriffing/test_backfill_tool.py
  tests/perf/auto_perf_sheriffing/test_secretary.py
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  tests/services/test_taskcluster.py
  treeherder/perf/auto_perf_sheriffing/__init__.py
  treeherder/perf/auto_perf_sheriffing/backfill_reports.py
  treeherder/perf/auto_perf_sheriffing/backfill_tool.py
  treeherder/perf/auto_perf_sheriffing/factories.py
  treeherder/perf/auto_perf_sheriffing/outcome_checker.py
  treeherder/perf/auto_perf_sheriffing/secretary.py
  treeherder/perf/auto_perf_sheriffing/sherlock.py
  treeherder/perf/management/commands/backfill_perf_jobs.py
  treeherder/perf/management/commands/perf_sheriff.py
  treeherder/services/taskcluster.py
Labels: python

#7092 Bug 1703507 - Enable Sherlock on Windows
  tests/perf/auto_perf_sheriffing/conftest.py
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  treeherder/config/settings.py
  treeherder/perf/auto_perf_sheriffing/secretary.py
  treeherder/perf/auto_perf_sheriffing/sherlock.py
  treeherder/perf/models.py
Labels: python

#7091 Bug 1703499 - Collapse performance tables in comment 0
  ui/perfherder/alerts/StatusDropdown.jsx
  ui/perfherder/helpers.js
Labels: javascript

#7098 Bug 1704514 - Fix broken backfill tool
  treeherder/perf/auto_perf_sheriffing/factories.py
  treeherder/perf/management/commands/backfill_perf_jobs.py
  treeherder/services/taskcluster.py
Labels: python

#7102 Bug 1704798 - Properly sort alerts within alert summary
  ui/perfherder/alerts/AlertTable.jsx
Labels: javascript

#7103 Bug 1704789 - Measurement unit is not showing correctly
  ui/perfherder/compare/CompareTable.jsx
Labels: javascript

#7108 Bug 1698548 - Link to Talos test documentation
  tests/ui/perfherder/alerts-view/alerts_table_row_test.jsx
  ui/css/perf.css
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertTableRow.jsx
  ui/perfherder/alerts/StatusDropdown.jsx
  ui/perfherder/compare/CompareTable.jsx
  ui/perfherder/compare/CompareTableControls.jsx
  ui/perfherder/compare/CompareTableView.jsx
  ui/perfherder/graphs/LegendCard.jsx
  ui/perfherder/helpers.js
  ui/perfherder/tests/TestsTable.jsx
  ui/perfherder/tests/TestsTableControls.jsx
Labels: javascript

#7097 Bug 1704020 - Fix field completion in email's table
  tests/perf/auto_perf_sheriffing/conftest.py
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  treeherder/perf/auto_perf_sheriffing/sherlock.py
  treeherder/perf/email.py
  treeherder/perf/migrations/0039_store_more_job_details_on_record.py
  treeherder/perf/models.py
Labels: db-schema-changes, python

#7106 Bug 1705366 - Sherlock targets incorrect alerts
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  treeherder/perf/auto_perf_sheriffing/backfill_reports.py
  treeherder/perf/auto_perf_sheriffing/sherlock.py
Labels: python

#7111 Bug 1706569 - Improperly built URLs for backfill report emails
  treeherder/perf/email.py
Labels: python
