Repository mozilla/treeherder, pull requests merged in 2021-07, with the labels that each got.

#7189 Bug 1717212 - Compare View query string parameters are not updated
  tests/ui/perfherder/compare-view/compare_table_test.jsx
  ui/perfherder/Validation.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
  ui/perfherder/compare/CompareTableControls.jsx
  ui/shared/FilterControls.jsx
  ui/shared/InputFilter.jsx
Labels: javascript

#7204 Bug 1719606 - Alerts View - Page does not reset when clicking header
  ui/perfherder/alerts/AlertsView.jsx
  ui/shared/InputFilter.jsx
Labels: javascript

#7186 Bug 1714038 - Enable pagination in Compare View
  tests/ui/mock/compare_table_controls.json
  tests/ui/perfherder/compare-view/compare_table_test.jsx
  ui/perfherder/alerts/AlertsViewControls.jsx
  ui/perfherder/compare/CompareTableControls.jsx
  ui/perfherder/compare/CompareTableView.jsx
  ui/perfherder/shared/Pagination.jsx
Labels: javascript

#7205 Bug 1719854 - Alerts View - add icon for graph link
  tests/ui/perfherder/alerts-view/alerts_table_row_test.jsx
  ui/perfherder/alerts/AlertTableRow.jsx
Labels: javascript

#7197 Bug 1718601 - Alerts View - Add copy alert ID button
  tests/ui/perfherder/alerts-view/alerts_test.jsx
  ui/perfherder/alerts/AlertHeader.jsx
  ui/perfherder/alerts/AlertHeaderTitle.jsx
  ui/shared/Clipboard.jsx
Labels: javascript

#7203 Bug 1719466 - Alert filtering based on OSX platform name is incorrect
  tests/perf/auto_perf_sheriffing/test_backfill_reports/conftest.py
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_alerts_picker.py
  treeherder/perf/auto_perf_sheriffing/backfill_reports.py
Labels: python

#7214 Bug 1720839 - Compare View Pagination links to pages are not shown when number of pages < 5
  tests/ui/perfherder/compare-view/compare_table_test.jsx
  ui/perfherder/compare/CompareTableControls.jsx
Labels: javascript

#7211 Bug 1719840 - Add backfill support for OSX as well
  tests/perf/auto_perf_sheriffing/conftest.py
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  treeherder/config/settings.py
Labels: python

#7212 Bug 1720447 - Alerts View - Refresh in place starred alerts
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertTableRow.jsx
Labels: javascript

#7183 Bug 1712731 - Compute the noise profile of the data when generating alerts.
  requirements/common.in
  requirements/common.txt
  tests/perfalert/test_alerts.py
  treeherder/perf/alerts.py
  treeherder/perf/migrations/0040_performancealert_noise_profile.py
  treeherder/perf/models.py
Labels: db-schema-changes, python
