Repository mozilla/treeherder, pull requests merged in 2021-01, with the labels that each got.

#6912 Bug 1681473 - Cannot expire multicommit data points
  tests/model/cycle_data/test_perfherder_cycling.py
  treeherder/perf/migrations/0036_cascade_perf_datum_deletion.py
Labels: db-schema-changes, python

#6910 Bug 1681880 TypeError: e[0] is undefined when hiding all data series
  ui/perfherder/graphs/GraphsContainer.jsx
Labels: javascript

#6919 Bug 1682764 - SQL syntax error when expiring `try` data
  tests/model/cycle_data/test_perfherder_cycling.py
  tests/webapp/api/test_performance_data_api.py
  treeherder/model/data_cycling/__init__.py
  treeherder/model/data_cycling/cyclers.py
  treeherder/model/data_cycling/max_runtime.py
  treeherder/model/data_cycling/removal_strategies.py
  treeherder/model/data_cycling/signature_remover.py
  treeherder/model/data_cycling/utils.py
  treeherder/model/management/commands/cycle_data.py
  treeherder/perf/data_cycling/__init__.py
Labels: python

#6920 Bug 1682849 - Irrelevant data removal strategy timing out
  treeherder/model/data_cycling/removal_strategies.py
Labels: python

#6943 Bug 1685037 - Email dhunt@mozilla.com is denylisted
  tests/model/cycle_data/test_perfherder_cycling.py
  treeherder/model/data_cycling/signature_remover.py
Labels: python

#6951 Add "browsertime" as a possible performance test in `isPerfTest`.
  ui/helpers/job.js
Labels: javascript

#6940 Bug 1679019 - Selecting the checkbox for an alert summary in perfherder should check only the untriaged alerts
  tests/ui/mock/alert_summary_with_different_status.json
  tests/ui/perfherder/alerts-view/select_alerts_dropdown_test.jsx
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/SelectAlertsDropdown.jsx
Labels: javascript

#6975 Bug 1681704 - Fix UI position for alert summary's status dropdown
  ui/css/perf.css
  ui/perfherder/alerts/AlertTable.jsx
Labels: javascript

#6974 Bug 1604871 - Unable to add data to graph when there are no recent results
  tests/ui/perfherder/graphs-view/timerange_dropdown_test.jsx
  ui/perfherder/graphs/GraphsView.jsx
  ui/perfherder/graphs/GraphsViewControls.jsx
  ui/perfherder/graphs/TestDataModal.jsx
  ui/perfherder/graphs/TimeRangeDropdown.jsx
Labels: javascript

#6971 Bug 1680433 - Wrong pushlog link in alert dropdown
  tests/webapp/api/test_performance_alertsummary_api.py
  tests/webapp/api/test_performance_data_api.py
  treeherder/webapp/api/performance_data.py
  ui/perfherder/graphs/GraphTooltip.jsx
Labels: javascript, python
