Repository mozilla/treeherder, pull requests merged in 2021-03, with the labels that each got.

#7006 Bug 1689620 - Soft launch backfill tool
  tests/conftest.py
  tests/extract/test_extract_alerts.sql
  tests/extract/test_extract_job.sql
  tests/model/cycle_data/test_perfherder_cycling.py
  tests/perf/auto_sheriffing_criteria/__init__.py
  tests/perf/auto_sheriffing_criteria/conftest.py
  tests/perf/auto_sheriffing_criteria/test_common_behaviour.py
  tests/perf/auto_sheriffing_criteria/test_criteria_tracker.py
  tests/perf/auto_sheriffing_criteria/test_engineer_traction.py
  tests/perf/auto_sheriffing_criteria/test_fix_ratio.py
  tests/perf/auto_sheriffing_criteria/test_nonblockable_session.py
  tests/perf/test_email.py
  tests/perfalert/conftest.py
  tests/perfalert/test_alert_modification.py
  tests/perfalert/test_alerts.py
  tests/perfalert/test_alerts/test_identify_retriggerables.py
  tests/perfalert/test_auto_perf_sheriffing/__init__.py
  tests/perfalert/test_auto_perf_sheriffing/conftest.py
  tests/perfalert/test_auto_perf_sheriffing/test_backfill_reports/__init__.py
  tests/perfalert/test_auto_perf_sheriffing/test_backfill_reports/conftest.py
  tests/perfalert/test_auto_perf_sheriffing/test_backfill_reports/test_alerts_picker.py
  tests/perfalert/test_auto_perf_sheriffing/test_backfill_reports/test_backfill_report_maintainer.py
  tests/perfalert/test_auto_perf_sheriffing/test_backfill_reports/test_identify_retriggerables.py
  tests/perfalert/test_auto_perf_sheriffing/test_backfill_tool.py
  tests/perfalert/test_auto_perf_sheriffing/test_perf_sheriff_bot.py
  tests/perfalert/test_auto_perf_sheriffing/test_secretary_tool.py
  tests/perfalert/test_backfill_tool.py
  tests/perfalert/test_perf_sheriff_bot.py
  tests/sample_data/perf_sheriff_bot/backfillTask.json
  tests/services/test_taskcluster.py
  tests/webapp/api/test_performance_alerts_api.py
  tests/webapp/api/test_performance_alertsummary_api.py
  treeherder/extract/extract_alerts.json
  treeherder/model/data_cycling/__init__.py
  treeherder/model/data_cycling/cyclers.py
  treeherder/model/data_cycling/email_service.py
  treeherder/model/data_cycling/signature_remover.py
  treeherder/model/models.py
  treeherder/perf/alerts.py
  treeherder/perf/auto_perf_sheriffing/__init__.py
  treeherder/perf/auto_perf_sheriffing/backfill_reports.py
  treeherder/perf/auto_perf_sheriffing/backfill_tool.py
  treeherder/perf/auto_perf_sheriffing/factories.py
  treeherder/perf/auto_perf_sheriffing/outcome_checker.py
  treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
  treeherder/perf/auto_perf_sheriffing/secretary_tool.py
  treeherder/perf/email.py
  treeherder/perf/management/commands/backfill_perf_jobs.py
  treeherder/perf/management/commands/perf_sheriff.py
  treeherder/perf/management/commands/synthesize_backfill_report.py
  treeherder/perf/migrations/0037_extend_backfill_record.py
  treeherder/perf/models.py
  treeherder/services/taskcluster.py
Labels: db-schema-changes, python

#7033 Bug 1641447 - Show measurement units in perfherder comparison view
  tests/ui/perfherder/compare-view/compare_table_test.jsx
  ui/perfherder/compare/CompareTable.jsx
  ui/perfherder/compare/CompareView.jsx
Labels: javascript

#7038 Bug 1570906 - Performance alert created from a [tier 3] job
  tests/etl/test_perf_data_adapters.py
  tests/test_utils.py
  treeherder/etl/perf.py
  treeherder/model/models.py
Labels: python

#7066 Bug 1700376 - Use consistent date time format
  ui/perfherder/alerts/AlertHeader.jsx
Labels: javascript

#7040 Bug 1690259 - Keep historical data
  docs/data_cycling.md
  tests/conftest.py
  tests/model/cycle_data/test_perfherder_cycling.py
  treeherder/model/data_cycling/removal_strategies.py
  treeherder/perf/models.py
Labels: python

#7065 Bug 1700327 - Properly notify when backfill bot goes to sleep
  treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
  treeherder/perf/management/commands/perf_sheriff.py
Labels: python

#7059 Bug 1699411 - Reduce filled bug summary
  tests/model/cycle_data/test_perfherder_cycling.py
  tests/ui/helpers/helpers_test.js
  tests/ui/perfherder/filled_bug_alerts/alert_summary_downstream_regressions.json
  tests/ui/perfherder/filled_bug_alerts/alert_summary_improvements_only.json
  tests/ui/perfherder/filled_bug_alerts/alert_summary_invalid_regressions.json
  tests/ui/perfherder/filled_bug_alerts/alert_summary_regressions_and_improvements.json
  tests/ui/perfherder/filled_bug_alerts/alert_summary_regressions_and_reassigned.json
  tests/ui/perfherder/filled_bug_alerts/alert_summary_regressions_and_reassigned_to_other.json
  tests/ui/perfherder/filled_bug_alerts/alert_summary_with_one_regression.json
  ui/perfherder/alerts/StatusDropdown.jsx
  ui/perfherder/constants.js
  ui/perfherder/helpers.js
Labels: javascript

#7074 Bug 1701692 - Fix backfill failure
  treeherder/services/taskcluster.py
Labels: python

#7067 Bug 1700606 - Expire garbage backfill reports
  tests/model/cycle_data/test_perfherder_cycling.py
  treeherder/model/data_cycling/cyclers.py
  treeherder/model/data_cycling/signature_remover.py
Labels: python

#7070 Bug 1700946 - Update BackfillRecord after soft launch
  tests/perfalert/test_auto_perf_sheriffing/test_perf_sheriff_bot.py
  tests/perfalert/test_auto_perf_sheriffing/test_secretary_tool.py
  treeherder/model/models.py
  treeherder/perf/auto_perf_sheriffing/outcome_checker.py
  treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
  treeherder/perf/auto_perf_sheriffing/secretary_tool.py
  treeherder/perf/email.py
  treeherder/perf/models.py
Labels: python
