Repository mozilla/treeherder, pull requests merged in 2021-05, with the labels that each got.

#6763 Bug 1626746 - Push health use mozci on backend
  .neutrinorc.js
  Procfile
  dev_mozci_config.toml
  docker-compose.yml
  mozci_config.toml
  requirements/common.txt
  tests/push_health/test_builds.py
  tests/push_health/test_compare.py
  tests/push_health/test_linting.py
  tests/push_health/test_tests.py
  tests/ui/mock/push_health.json
  tests/ui/push-health/Action_test.jsx
  tests/ui/push-health/ClassificationGroup_test.jsx
  tests/ui/push-health/CommitHistory_test.jsx
  tests/ui/push-health/PlatformConfig_test.jsx
  tests/ui/push-health/TestMetric_test.jsx
  tests/ui/push-health/details/DetailsPanel_test.jsx
  treeherder/config/settings.py
  treeherder/log_parser/failureline.py
  treeherder/push_health/builds.py
  treeherder/push_health/classification.py
  treeherder/push_health/compare.py
  treeherder/push_health/filter.py
  treeherder/push_health/linting.py
  treeherder/push_health/performance.py
  treeherder/push_health/tests.py
  treeherder/push_health/utils.py
  treeherder/webapp/api/push.py
  ui/helpers/display.js
  ui/push-health/Action.jsx
  ui/push-health/ClassificationGroup.jsx
  ui/push-health/CommitHistory.jsx
  ui/push-health/Health.jsx
  ui/push-health/MyPushes.jsx
  ui/push-health/PlatformConfig.jsx
  ui/push-health/TaskSelection.jsx
  ui/push-health/Test.jsx
  ui/push-health/TestMetric.jsx
  ui/push-health/helpers.js
  ui/shared/StatusButton.jsx
Labels: mozci

#7113 FXP-1593 - Don't backfill the same job
  tests/perf/auto_perf_sheriffing/test_backfill_reports/test_backfill_report_maintainer.py
  treeherder/perf/auto_perf_sheriffing/backfill_reports.py
  treeherder/perf/models.py
Labels: python

#7150 Bug 1706469 - Perfherder comparison just hangs
  ui/perfherder/compare/CompareTableView.jsx
  ui/perfherder/compare/CompareView.jsx
Labels: javascript

#7084 Bug 1698835 - Integrate PollyJs into Perfherder
  .eslintrc.js
  .neutrinorc.js
  docs/testing.md
  jest-puppeteer.config.js
  package.json
  tests/ui/integration/graphs-view/graphs_view_integration_test.jsx
  tests/ui/integration/recordings/GraphsViewRecord-Test-Pupeteer_1324652544/Record-requests_2171382282/recording.har
  tests/ui/integration/test-setup.js
  ui/perfherder/graphs/GraphsViewControls.jsx
  yarn.lock
Labels: javascript
