Repository mozilla/treeherder, pull requests merged in 2021-09, with the labels that each got.

#7244 Bug 1725577 - Aggregate auto backfill emails to daily frequency
  tests/perf/auto_perf_sheriffing/conftest.py
  tests/perf/auto_perf_sheriffing/test_report_backfill_outcome.py
  tests/perf/auto_perf_sheriffing/test_sherlock.py
  treeherder/perf/auto_perf_sheriffing/factories.py
  treeherder/perf/auto_perf_sheriffing/sherlock.py
  treeherder/perf/management/commands/report_backfill_outcome.py
  treeherder/perf/migrations/0041_backfillnotificationrecord.py
  treeherder/perf/models.py
Labels: python, db-schema-changes

#7256 FXP-1560 - Present backill status of alerts
  tests/ui/mock/alert_summaries.json
  tests/ui/mock/alert_summary_very_big.json
  tests/ui/perfherder/alerts-view/alerts_test.jsx
  treeherder/webapp/api/performance_serializers.py
  ui/perfherder/alerts/AlertTableRow.jsx
  ui/perfherder/perf-helpers/constants.js
Labels: python, javascript

#7259 Bug 1725334 - Graphs View - Page does not reset when clicking header fixed
  ui/perfherder/graphs/GraphsView.jsx
Labels: javascript

#7263 Bug 1729425 - Tests View - Page does not reset when clicking header
  ui/perfherder/tests/TestsView.jsx
Labels: javascript

#7265 Bug 1729635 - Create a bug template for devtools regressions
  treeherder/perf/fixtures/performance_bug_templates.yaml
Labels: db-schema-changes

#7270 Bug 1730892 - Remove duplication from tags/options from alerts view
  tests/ui/perfherder/alerts-view/alerts_table_row_test.jsx
  ui/perfherder/alerts/AlertTableRow.jsx
  ui/perfherder/alerts/AlertTableTagsOptions.jsx
Labels: javascript

#7264 Bug 1724939 - Display noise profile for alerts
  tests/ui/mock/alert_summaries.json
  tests/ui/mock/alert_summary_very_big.json
  tests/ui/perfherder/alerts-view/alerts_table_row_test.jsx
  tests/webapp/api/test_performance_alerts_api.py
  tests/webapp/api/test_performance_alertsummary_api.py
  treeherder/webapp/api/performance_serializers.py
  ui/perfherder/alerts/AlertTable.jsx
  ui/perfherder/alerts/AlertTableRow.jsx
  ui/perfherder/alerts/BadgeTooltip.jsx
  ui/perfherder/perf-helpers/constants.js
  ui/perfherder/perf-helpers/sort.js
Labels: python, javascript
